#!/usr/bin/env bash

# Install nginx
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80
sed -i 's/^\(listen\s*\)[[:digit:]]*\(.*$\)/\180/' /etc/nginx/sites-available/default

# Start nginx
service nginx start

# Configure default server block to return "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Check that nginx is accepting traffic on port 80
curl -s -o /dev/null -w "%{http_code}" http://localhost/ | grep 200

# Check that nginx returns "Hello World!" at its root
curl -s http://localhost/ | grep "Hello World!"
