#!/usr/bin/env bash
# Displays information about the file `school`.

if [ -e "school" ]
then
  echo "School file exists"
  if [ -s "school" ]
  then
    echo "Shool file is not empty"
  else
    echo "Shool file is empty"
  fi

  if [ -f "school" ]
  then
    echo "School is a regular file"
  fi
else
  echo "School file does not exist"
fi
